Dop 5071
mongodb/netlify-extensions pull request #17
Opened 2024-10-15 14:08 UTC by anabellabuckvar

2024-10-22 15:43 UTC, cbush commented on populate-metadata/src/atlasConnector.ts
> +  if (clusterZeroClient) {
Better not to make a blank if just for else
```suggestion
  if (!clusterZeroClient) {
```

2024-10-22 15:43 UTC, cbush commented on populate-metadata/src/atlasConnector.ts
> +  } else {
```suggestion
```

2024-10-22 15:43 UTC, cbush commented on populate-metadata/src/atlasConnector.ts
> +  return clusterZeroClient.db(ENV_VARS.POOL_DB_NAME);
Configuration should be passed in from above, not drawn from env

2024-10-22 15:43 UTC, cbush commented on populate-metadata/src/atlasConnector.ts
> +    console.info('No client connection open to Snooty Db');
```suggestion
    console.info('No client connection open to database');
```

2024-10-22 15:43 UTC, cbush commented on populate-metadata/src/extension.ts
> +export const envVarToBool = (envVar: boolean | string = 'false') => {
Declare return types on exported functions
```suggestion
export const envVarToBool = (envVar: boolean | string = 'false'): boolean => {
```

2024-10-22 15:43 UTC, cbush commented on populate-metadata/src/extension.ts
> +  // In case of issues, double check that BuildConfigSchema is in correct spot within the order of type params
Comment applies to BuildContext too, might want to move it up one line

2024-10-22 15:43 UTC, cbush commented on populate-metadata/src/extension.ts
> +          return options?.if === undefined || options.if(buildConfig);
Could use a comment here explaining the intention

2024-10-22 15:43 UTC, cbush commented on populate-metadata/src/getProperties.ts
> +    default:
This whole function could just be
```ts
return Object.fromEntries([[env ?? "prd", 1]]);
```

But the explicit env names does give me pause - will need to keep reading to see

2024-10-22 15:43 UTC, cbush commented on populate-metadata/src/getProperties.ts
> +    throw new Error('Error while getting docsets entry in Atlas');
What error?

2024-10-22 16:01 UTC, seungpark reviewed
left a few comments on setting env vars. 

owed another review for app routing and the UI (is this required?)

2024-10-22 16:30 UTC, anabellabuckvar commented on populate-metadata/src/extension.ts
> +  // In case of issues, double check that BuildConfigSchema is in correct spot within the order of type params
Yes

2024-10-22 20:04 UTC, anabellabuckvar commented on populate-metadata/src/extension.ts
> +> extends NetlifyExtension<
The idea is, as Chris and I discussed, to not require that each engineer developing an extension implement extension enablement logic, as that could be prone to errors. This way there's a standardized method for extension enablement, too. @cbush, please correct me or elaborate if I've missed anything

2024-10-22 20:06 UTC, anabellabuckvar commented on populate-metadata/src/index.ts
> +  isEnabled: envVarToBool(process.env.POPULATE_METADATA_ENABLED),
We usually would! However, we should still be able to easily enable/disable extensions teamwide and on specific sites. Right now, for example, the extension is in development, so it's only enabled on very few sites

2024-10-22 20:08 UTC, anabellabuckvar commented on populate-metadata/src/updateConfig.ts
> +    process.env.ENV = isWebhookDeploy ? 'dotcomprd' : 'prd';
Good catch! This should be `config.build.environment` instead. Updated to reflect this

2024-10-22 20:09 UTC, anabellabuckvar commented on populate-metadata/src/updateConfig.ts
> +    config.build.environment.PRODUCTION = isWebhookDeploy;
Going to remove `PRODUCTION` as now `config.build.environment.ENV` can signify an S3 upload (`dotcomstg` and `dotcomprd`)

2024-10-22 21:00 UTC, anabellabuckvar commented on populate-metadata/src/assertEnvVars.ts
> +    REPOS_BRANCHES_COLLECTION: `${process.env.REPOS_BRANCHES_COLLECTION}`,
It's set In the UI as an environment variable: "pool" as the teamwide environment variable and "pool_test" only in the "snooty-mongodb" site

2024-10-22 21:12 UTC, anabellabuckvar commented on populate-metadata/src/extension.ts
> +  return JSON.parse(envVar) as boolean;
It should throw an error if not `true`, `false`, or undefined

2024-10-24 17:19 UTC, seungpark commented on populate-metadata/src/extension.ts
> +> extends NetlifyExtension<
i am fine with a standardization of extension enablement, but don't different extensions have different dependencies on whether to run or not? it seems like the `if` should be determined using build/env vars to determine if extension is enabled/disabled CMIIW

2024-10-24 20:17 UTC, anabellabuckvar commented on populate-metadata/src/extension.ts
> +> extends NetlifyExtension<
Yup! That's exactly what this Extension class is doing/standardizing

2024-10-25 13:47 UTC, seungpark reviewed
think we should be setting more env vars (ie. database names and collection names) based on the ENV variable set, but otherwise looks great!

2024-10-25 13:47 UTC, seungpark commented on populate-metadata/src/server/router.ts
>          enabled: !!enabledVar,
what is the difference between this enable and extension `if`? IIUC, this is for the UI, where they can explicitly disable/enable the extension

for future reference, I think PR would be much cleaner with 1) initial PR for boilerplate without UI and 2) PR to add / update logic for populate metadata targeted towards boilerplate, and UI can be a follow up

2024-10-25 13:47 UTC, seungpark commented on populate-metadata/src/extension.ts
> +  return JSON.parse(envVar);
see previous thread!

2024-10-25 13:47 UTC, seungpark commented on populate-metadata/src/assertDbEnvVars.ts
> +    POOL_DB_NAME: `${process.env.MONGO_ATLAS_POOL_DB_NAME}` as PoolDbName,
do these not depend on the ENV variable? feels like theres a disconnect here where we should allow these to be derived from ENV (possibly in updateConfig)

2024-10-25 16:28 UTC, seungpark commented on populate-metadata/src/extension.ts
> +> extends NetlifyExtension<
write a comment TODO to move this out of populate-metadata module

2024-10-25 16:30 UTC, seungpark commented on populate-metadata/src/index.ts
> +  isEnabled: envVarToBool(process.env.POPULATE_METADATA_ENABLED),
Drop in a ticket to keep track of env variables used in netlify

2024-10-25 16:32 UTC, seungpark commented on populate-metadata/src/updateConfig.ts
> +  configEnvironment.ENV =
ie. (read a separate env variable, but fallback to logic from env) like BRANCH_NAME

2024-10-25 22:48 UTC, anabellabuckvar commented on populate-metadata/src/server/router.ts
>          enabled: !!enabledVar,
For sure. Good idea, thank you

2024-10-28 14:28 UTC, biancalaube requested changes

2024-10-28 14:28 UTC, biancalaube commented on populate-metadata/src/index.ts
> +  isEnabled: envVarToBool(process.env.POPULATE_METADATA_ENABLED),
just wanted to mention in the readme of this PR you said in the testing section to enable `ENABLE_POPULATE_METADATA` but I think you meant to write `POPULATE_METADATA_ENABLED` so it matches this env variable

2024-10-28 14:28 UTC, biancalaube commented on populate-metadata/src/ui/surfaces/SiteConfiguration.tsx
> +    <SiteConfigurationSurface>
no a correction just a question, what exactly is the purpose for this file? are we able to see the below html somewhere? Like on the extension site?

2024-10-28 14:28 UTC, biancalaube commented on populate-metadata/src/extension.ts
> +import type z from 'zod';
i see this import is used for the schema. Just curious as to why we are using zod since I havent heard/used it before. Has this been used before on the team or is this the first time using it for extensions? Just trying understand the stack better

2024-10-28 14:37 UTC, anabellabuckvar commented on populate-metadata/src/ui/surfaces/SiteConfiguration.tsx
> +    <SiteConfigurationSurface>
This file is part of the boilerplate code created by Netlify upon extension created. Netlify's stated purpose of supplying this UI directory is to help developers create UIs for their extensions

2024-10-28 18:02 UTC, anabellabuckvar commented on populate-metadata/src/extension.ts
> +import type z from 'zod';
Discussed async!

2024-10-29 17:25 UTC, seungpark commented on populate-metadata/src/updateConfig.ts
> +    default:
minor, either explicitly define for 'stg' and repeat, or put a comment here for 'stg'

2024-10-29 18:04 UTC, seungpark approved these changes
minor comments below but overall looks good. think there are a few TODO ie. ! [making an "extended extension"](https://github.com/mongodb/netlify-extensions/pull/17/files#diff-3913fcbc85d9b01e445dd9cbb93bab311cc0d59879355906074f084aa7626edfR34) :D that can be converted to tickets please!

2024-10-29 18:52 UTC, anabellabuckvar commented on populate-metadata/src/extension.ts
> +import type z from 'zod';
We're using it because we are extending the `NetlifyExtension` class in which Netlify uses zod for typing, as you can see [here](https://github.com/mongodb/netlify-extensions/pull/17/files/6708e97e00f430c847ce3163a274262cce6207a7#diff-3913fcbc85d9b01e445dd9cbb93bab311cc0d59879355906074f084aa7626edfR35-R45). Furthermore, since we're overriding the `addBuildEventHandler` from the parent `NetlifyExtension` class, we need to ensure that the new method is compatible with the original one in terms of the input parameters and return value using zod [here](https://github.com/mongodb/netlify-extensions/pull/17/files/6708e97e00f430c847ce3163a274262cce6207a7#diff-3913fcbc85d9b01e445dd9cbb93bab311cc0d59879355906074f084aa7626edfR55-R63)

2024-10-29 20:34 UTC, anabellabuckvar commented on populate-metadata/src/extension.ts
> +> extends NetlifyExtension<
https://jira.mongodb.org/browse/DOP-5009

2024-10-30 13:48 UTC, biancalaube approved these changes
LGTM !

2024-10-30 14:13 UTC, merged