DOP-5076: Move mut-redirects and mut-publish
mongodb/netlify-extensions pull request #22
Opened 2024-10-25 18:46 UTC by biancalaube

### Ticket

[DOP-5076](https://jira.mongodb.org/browse/DOP-5076)

### Links 

[Extension site](https://app.netlify.com/sites/redirects-and-publish-extension/deploys)

[docs-landing testing site](https://app.netlify.com/sites/bianca-fork-docs-landing/deploys/671bd80837fc878bd8759327)
[bucket for docs-landing (in a testing dir)](https://us-east-2.console.aws.amazon.com/s3/buckets/docs-mongodb-org-dotcomstg?region=us-east-2&bucketType=general&prefix=netlify/&showversions=false)

[cloud-docs testing site](https://app.netlify.com/sites/cloud-docs-bianca-fork/deploys/671be10692866d98519a0659)
[bucket for cloud-docs testing](https://us-east-2.console.aws.amazon.com/s3/buckets/docs-atlas-dotcomstg?region=us-east-2&bucketType=general&prefix=netlify/docs-qa/&showversions=false)

### Testing

* on a forked site enable the variable `MUT_COMMANDS_ENABLED` to true in the environment variables for the site on netlify
* in the deploy logs check that its uploading the s3 bucket
* i have some comments in the index.ts file of TODO's, please respond if you have any opinions of the things I mentioned
* Also side note, the reason I have so many extra files is because when i was creating a new extension i chose the format of 'buildevent handlers' and it gave me all those extra files as well for formatting. Not sure if necessary but didnt want to get rid of them since they were downloaded with all the other extension stuff and i didnt want the extension not to work.

2024-10-29 16:15 UTC, rayangler commented on redirects-and-publish/src/searchConnector.ts
> +      `Error getting ${collection} collection from client: ${dbSession}`,
(Question) Just wondering: When is an error expected here?

2024-10-29 16:15 UTC, rayangler commented on redirects-and-publish/src/index.ts
> +  },
Would it be possible to explicitly close the connections of the two MongoClients we use in a `finally` block? This should help ensure that we're closing them, regardless of success or failure

2024-10-29 16:15 UTC, rayangler commented on redirects-and-publish/src/searchConnector.ts
> +export const getSearchDb = async () => {
Is this database used anywhere? If not, can we remove?

2024-10-30 21:13 UTC, biancalaube commented on redirects-and-publish/src/index.ts
> +        'No repo name supplied as environment variable, manifest cannot be uploaded to Atlas Search.Documents collection ',
Thats a good point thanks for catching that , I'e updated it so they should all be starting with upper case now

2024-10-31 13:55 UTC, biancalaube commented on redirects-and-publish/src/server/router.ts
> +        ?.values.find((val) => val.context === 'all');
So from my understanding the site that disable/enable the extension still uses the environment variable that we have been using. (line 5 of router.ts) However I know we are switching to our own extension class. @anabellabuckvar do you know if the code changes in the new extension class allow for this ui page still to work ?
https://app.netlify.com/sites/cloud-docs-bianca-fork/extensions/x833a4cn-redirects-and-publish-extension

2024-10-31 13:56 UTC, biancalaube commented on redirects-and-publish/src/getProperties.ts
> +  console.log('connectiong to mongodb...');
yes thank you

2024-10-31 14:02 UTC, biancalaube commented on redirects-and-publish/src/searchConnector.ts
> +  const client = new mongodb.MongoClient(uri);
sorry could you explain further on what you mean by this ? Like how to add `appName` exactly? Sorry Im just not too familiar with this code, I copied it over from search-manifest initially.

2024-10-31 14:30 UTC, rayangler commented on redirects-and-publish/src/searchConnector.ts
> +  const client = new mongodb.MongoClient(uri);
No worries. `MongoClient` can [accept options](https://www.mongodb.com/docs/drivers/node/current/fundamentals/connection/connection-options/#:~:text=Description-,appName,-string) like an `appName`. Something like this:

```js
const appName = 'redirects-and-publish-extension';
const client = new MongoClient(uri, { appName });
```

By doing so, whenever this extension makes a query, the db cluster will include the same `appName` in a log output so that if we ever need to debug something directly in the db, we know what app made that connection. [Here](https://www.mongodb.com/docs/manual/reference/log-messages/#:~:text=%22appName%22%3A%22MongoDB%20Shell%22%2C) is a docs example of a log output with an `appName`.

2024-10-31 17:43 UTC, anabellabuckvar commented on redirects-and-publish/src/manifestEntry.ts
We can remove this file, it shouldn't be needed for the `redirects-and-publish` extension

2024-11-07 19:03 UTC, seungpark reviewed
few comments below! PTAL!

2024-11-07 19:03 UTC, seungpark commented on redirects-and-publish/src/index.ts
> +  if (!process.env.MUT_COMMANDS_ENABLED) return;
IIUC, this will be temporary until we migrate CDN to netlify sites (?)

which means this will only run when `netlifyConfig.build.environment.ENV` is dotcomstg and dotcomprd values ?

2024-11-07 19:04 UTC, seungpark commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +      await run.command('cp -r AWSCLIV2.pkg build.sh bundle.zip CHANGELOG.md code-of-conduct.md component-factory-transformer docs-landing gatsby-browser.js gatsby-config.js gatsby-ssr.js jest.config
i guess the drawback here is that it would inject these prefixes into the netlify preview sites (which i am fine with)

2024-11-07 21:12 UTC, biancalaube commented on redirects-and-publish/src/searchConnector.ts
> +  const client = new mongodb.MongoClient(uri);
This will be resolved in future ticket, talked about it with anabella

2024-11-07 21:25 UTC, biancalaube commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +      await run.command('cp -r AWSCLIV2.pkg build.sh bundle.zip CHANGELOG.md code-of-conduct.md component-factory-transformer docs-landing gatsby-browser.js gatsby-config.js gatsby-ssr.js jest.config
Hi seung, wondering if you still wanted me to make these changes as after the meeting it sounds like we are leaving this functionality in this extension instead of the build.sh

2024-11-07 21:35 UTC, biancalaube commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +      if (configEnvironment?.SITE_NAME === "mongodb-snooty") {
From my understanding I dont we think we can. This is because for the mongodb-snooty site we needed to clone in docs-landing so the path will be different. The one thing i can think of is to do two different `cp` commands at the beginning of the build_event_handler to put the `config/redirects` folder in the new snooty folder but I'm not sure if thats the solution you were thinking of.

2024-11-07 21:39 UTC, biancalaube commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +    //TODO: change these teamwide env vars in Netlify UI when ready to move to prod
sorry im a little confused by this comment. What do yo meant by `___`

2024-11-07 21:41 UTC, seungpark commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +    //TODO: change these teamwide env vars in Netlify UI when ready to move to prod
oh i mean whatever else uses these variables. i believe it was the populate-metadata extension

2024-11-07 21:42 UTC, seungpark commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +      await run.command('cp -r AWSCLIV2.pkg build.sh bundle.zip CHANGELOG.md code-of-conduct.md component-factory-transformer docs-landing gatsby-browser.js gatsby-config.js gatsby-ssr.js jest.config
to make a copy is fine but do we need all these still? i feel like the top comment is still valid where we can just copy snooty and the zip bundle CMIIW please

2024-11-07 22:02 UTC, biancalaube commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +      console.log('In the bucket of', docsetEntry?.bucket, docsetEntry?.bucket?.dotcomstg); // subbed in docs-mongodb-org-dotcomstg
From my understand this what returned from a docs-entry
```
Succesfully got docsets entry: {
   project: 'landing',
   bucket: { dotcomstg: 'docs-mongodb-org-dotcomstg' },
   prefix: { dotcomstg: 'docs-qa' },
   url: {
     dotcomstg: 'https://mongodbcom-cdn.website.staging.corp.mongodb.com/'
   }
}
```

so when I try to do `docsetEntry?.bucket?.configEnvironment.ENV` its erroring because of the type configuration. Is there another way to do this because I think im misunderstanding what you want.

2024-11-07 22:04 UTC, biancalaube commented on redirects-and-publish/src/index.ts
> +  if (!process.env.MUT_COMMANDS_ENABLED) return;
yes we only want to run this extension on dotcomstg and dotcomprd

2024-11-07 22:16 UTC, biancalaube commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +const MUT_VERSION = '0.11.4';
updated!

2024-11-07 22:23 UTC, biancalaube commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +      await run.command('cp -r AWSCLIV2.pkg build.sh bundle.zip CHANGELOG.md code-of-conduct.md component-factory-transformer docs-landing gatsby-browser.js gatsby-config.js gatsby-ssr.js jest.config
the problem with the `mongodb-snooty` site is that there is no snooty folder to copy, all the contents of snooty are just in the base directory. and i tried to run `cp -r ./* running-mut` but netlify doesn't like for some reason the `*` symbol. And when I tried `cp -r . running-mut` it didnt let me since the `running-mut` folder is inside the directory im trying to copy all the contents from.

2024-11-07 22:23 UTC, biancalaube commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +    process.env.PATH_PREFIX = '/docs-qa';
I've made a fix for this, let me know what you think

2024-11-07 22:25 UTC, biancalaube commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +      if (configEnvironment?.SITE_NAME === "mongodb-snooty") {
this is for the `mut-redirects` command so im not sure, @anabellabuckvar might know more if this is needed or not.

2024-11-07 22:28 UTC, biancalaube commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +      } else if (docsetEntry?.bucket?.dotcomprd !== undefined) { // we will want to do this in the future but not in this PR
I've updated the conditional statement for this to be more clean with the `configEnviroment.ENV`. But yes, this extension would only run either `dotcomstg` or `dotcomprd` depending on the values recevied from populate-metadata.

2024-11-08 16:50 UTC, seungpark requested changes
see comments below! sorry for the comments on outdated files previously. made new ones in current changes and resolving the old ones

2024-11-08 16:50 UTC, seungpark commented on redirects-and-publish/src/index.ts
> +    await mutRedirectsAndPublish(netlifyConfig?.build?.environment, run);
since we want it to run only on those two env `dotcomstg` and `dotcomprd`, should return early if not those env

2024-11-08 16:50 UTC, seungpark commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +  if (configEnvironment.ENV !== 'dotcomstg') {
see comment above. can do earlier. also don't forget dotcomprd

2024-11-08 16:50 UTC, seungpark commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +      'cp -r AWSCLIV2.pkg build.sh bundle.zip CHANGELOG.md code-of-conduct.md component-factory-transformer docs-landing gatsby-browser.js gatsby-config.js gatsby-ssr.js jest.config.js jest-preproces
perhaps better to use `rsync` than cp here. [example here](https://github.com/mongodb/netlify-extensions/pull/31/files#diff-940e8879c65b25610de2af8b9539b817681ad1e6b1ca3f4187b8ca4802b4b401R7-R9) with[ log](https://app.netlify.com/sites/iridescent-babka-0105eb/deploys/672be2d4dff07e5c6114b041#L840):

2024-11-08 16:50 UTC, seungpark commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +const MANIFEST_PATH = `${process.cwd()}/bundle.zip`;
a bit confusing here as we are passing this original bundle.zip to env variables for the copied snooty, but creating a copy in the `cp` command

2024-11-08 16:50 UTC, seungpark commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +  process.env.PATH_PREFIX = `/${docsetEntry?.prefix?.dotcomstg}` ?? '/docs-qa';
```suggestion
  process.env.PATH_PREFIX = `/${docsetEntry?.prefix?.[configEnvironment.ENV]}` ?? '/docs-qa';
```

2024-11-08 16:50 UTC, seungpark commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +      await run.command(
minor - we can set the redirects location path and call the command once with interpolated string!

2024-11-08 16:50 UTC, seungpark commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +  if (!process.env.AWS_ACCESS_KEY_ID || !process.env.AWS_SECRET_ACCESS_KEY) {
throwing for missing config values can be done before copying so we can exit earlier

2024-11-08 16:50 UTC, seungpark commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +  if (!repoName) {
similar here

2024-11-08 16:50 UTC, seungpark commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +    if (configEnvironment.ENV === 'dotcomstg') {
remove the `if` condition and update the prefix and deployed urls to be:

`docsetEntry?.prefix?.[configEnvironment.ENV]` and `docsetEntry?.url?.[configEnvironment.ENV]`

2024-11-08 18:52 UTC, biancalaube commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +      'cp -r AWSCLIV2.pkg build.sh bundle.zip CHANGELOG.md code-of-conduct.md component-factory-transformer docs-landing gatsby-browser.js gatsby-config.js gatsby-ssr.js jest.config.js jest-preproces
i dont think the rsync will work since i still dont have any snooty repo to clone, these were the errors i was getting when i tried 
https://app.netlify.com/sites/mongodb-snooty/deploys/672e5c5d3788650008727da5

2024-11-08 19:01 UTC, biancalaube commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +const MANIFEST_PATH = `${process.cwd()}/bundle.zip`;
I think it's because when its a content repo instead of the mongodb-snooty site the bundle.zip is not in the snooty folder. So to make it consistent between the two we use the original. I could be misinterpreting it though, maybe @anabellabuckvar or @branberry would have more info? Should we not be using the original bundle.zip ?

2024-11-08 19:13 UTC, anabellabuckvar commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +  process.env.PATH_PREFIX = `/${docsetEntry?.prefix?.dotcomstg}` ?? '/docs-qa';
@seungpark what do you think about leaving this as is until we are ready to use Netlify for dotcomprd, and just add a 'TODO' comment to change it in the future? I know we check for the environment earlier in this extension, but if that is removed for some reason/accidentally, then this will start uploading to dotcomprd.

2024-11-08 19:15 UTC, anabellabuckvar commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +  const repoName = process.env.REPO_NAME ?? configEnvironment?.SITE_NAME;
I don't believe we need `repoName` for anything, it should be able to be removed

2024-11-08 19:19 UTC, anabellabuckvar commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +        `${process.cwd()}/mut/mut-redirects docs-landing/config/redirects -o public/.htaccess`,
nit: Can we add a TODO comment to change this from hardcoded docs-landing to whatever repo is being built once [DOP-5159](https://jira.mongodb.org/browse/DOP-5159) is completed?

2024-11-08 20:34 UTC, biancalaube commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +        `${process.cwd()}/mut/mut-redirects docs-landing/config/redirects -o public/.htaccess`,
this is harded coded since the mongodb-snooty site is always docs landing (from the build file) the command after this will build which repo this is ran on. So this code should work in theory for any content repo, should I add a check somewhere that it should only build for `mongodb-snooty` and `docs-landing` ?

2024-11-08 20:44 UTC, biancalaube commented on redirects-and-publish/src/index.ts
> +    await mutRedirectsAndPublish(netlifyConfig?.build?.environment, run);
added a new if statement, let me know what you think

2024-11-08 20:45 UTC, biancalaube commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +  process.env.PATH_PREFIX = `/${docsetEntry?.prefix?.dotcomstg}` ?? '/docs-qa';
I added a TODO, let me know what you guys think.

2024-11-08 20:59 UTC, anabellabuckvar commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +        `${process.cwd()}/mut/mut-redirects docs-landing/config/redirects -o public/.htaccess`,
At the moment, mongodb-snooty site always builds docs landing, but DOP-5159 is for being able to build any content repo on the mongodb-snooty site- once that ticket is completed, in theory, we should be able to build a different content repo on mongodb-snooty such as cloud-docs, in which case `docs-landing` won't always be the name of the directory containing the redirects file, rather it will live in `repoEntry.repoName/config/redirects`

2024-11-11 14:39 UTC, biancalaube commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +        `${process.cwd()}/mut/mut-redirects docs-landing/config/redirects -o public/.htaccess`,
okay that makes sense, I'll add the comment. thanks for the explanation

2024-11-11 14:50 UTC, biancalaube commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +      await run.command(
updated this line, let me know if it is what you wanted

2024-11-11 14:53 UTC, biancalaube commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +    if (configEnvironment.ENV === 'dotcomstg') {
added a comment to change this in the future for when we also want to do it for dotcomprd, for now i got rid of the if statement

2024-11-11 16:14 UTC, branberry commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +      'cp -r AWSCLIV2.pkg build.sh bundle.zip CHANGELOG.md code-of-conduct.md component-factory-transformer docs-landing gatsby-browser.js gatsby-config.js gatsby-ssr.js jest.config.js jest-preproces
@seungpark `rsync` would be better for sure, but unfortunately we don't have access to `rsync` in the worker for Netlify

2024-11-11 16:19 UTC, branberry commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +      'cp -r AWSCLIV2.pkg build.sh bundle.zip CHANGELOG.md code-of-conduct.md component-factory-transformer docs-landing gatsby-browser.js gatsby-config.js gatsby-ssr.js jest.config.js jest-preproces
@seungpark Yes! Good call-out. `rsync` would be a great option here. @biancalaube, what did you use for the `rsync` command exactly?

2024-11-11 20:02 UTC, seungpark reviewed
see comments below. think the `mongodb-snooty` is becoming too much of a stray, and should be consolidated into a regular `prd` (preferable) or `dotcomstg` environment so that we don't have to consider it in off cases, or skip mut publish for this and handle in a separate ticket

2024-11-11 20:02 UTC, seungpark commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +      docsetEntry?.bucket?.dotcomstg,
these should not be hardcoded env. i see in the [latest log](https://app.netlify.com/sites/cloud-docs-bianca-fork/deploys/6729324f722f3d67ca7f37c8#L1397) that this is undefined due to no docset entry as well. should be reading the incoming env from populate-metadata. 

cc @anabellabuckvar [is this correct](https://github.com/mongodb/netlify-extensions/blob/main/extensions/populate-metadata/src/updateConfig.ts#L103)? im not sure why `dotcomtstg` would only be for `SITE_NAME === 'mongodb-snooty'` and `webhook deploy or branch = main` ?

2024-11-11 21:45 UTC, anabellabuckvar commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +  process.env.GATSBY_MANIFEST_PATH = MANIFEST_PATH;
Is it necessary to set both `process.env.GATSBY_MANIFEST_PATH` and `process.env.MANIFEST_PATH`, especially since they are set to the same value?

2024-11-11 21:52 UTC, anabellabuckvar commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +    await run.command('rm -f -r running-mut/snooty');
I believe this is redundant since `await run.command('rm -f -r running-mut');` already removes  the`running-mut` folder and all it's subdirectories

2024-11-11 21:57 UTC, anabellabuckvar commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +      'cp -r AWSCLIV2.pkg build.sh bundle.zip CHANGELOG.md code-of-conduct.md component-factory-transformer docs-landing gatsby-browser.js gatsby-config.js gatsby-ssr.js jest.config.js jest-preproces
I believe there are a bunch of these files/folders that we don't need to copy: `bundle.zip`, `changelog.md`, `code-of-conduct.md`, `netlify.toml`, `README.md`, `snooty-parser`, `snooty-parser.zip`, at the least

@seungpark @branberry Please remove any I've incorrectly identified

2024-11-11 22:00 UTC, anabellabuckvar commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +    await run.command('ls running-mut/snooty');
Could you remove this before merging?

2024-11-11 22:00 UTC, anabellabuckvar commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +  await run.command('ls running-mut/snooty');
See previous comment about removal

2024-11-11 22:07 UTC, anabellabuckvar reviewed
Super nit: Could you capitalize your comments please 😅

2024-11-12 14:17 UTC, biancalaube commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +  process.env.GATSBY_MANIFEST_PATH = MANIFEST_PATH;
I might be wrong, but I dont think we have a `process.env.MANIFEST_PATH` , we just have
`MANIFEST_PATH = ${process.cwd()}/bundle.zip` that isnt a environment variable.

2024-11-12 19:42 UTC, biancalaube commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +    await run.command('rm -f -r running-mut/snooty');
nice catch! removed

2024-11-12 19:42 UTC, biancalaube commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +      'cp -r AWSCLIV2.pkg build.sh bundle.zip CHANGELOG.md code-of-conduct.md component-factory-transformer docs-landing gatsby-browser.js gatsby-config.js gatsby-ssr.js jest.config.js jest-preproces
Do you still want me to exclude them now that i changed this command to `rysnc`

2024-11-12 20:00 UTC, biancalaube commented
@anabellabuckvar @seungpark @branberry @rayangler 
Just committed new changes, changed it so on mongodb-snooty we are going to use `rsync` instead of `cp`. Also left in `dotcomstg` hardcoded for now while we are not ready for production, created [DOP-5178](https://jira.mongodb.org/browse/DOP-5178) to convert these hard coded values for when we are ready to move. Please let me know of more changes you wish to see !

2024-11-12 21:46 UTC, anabellabuckvar commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +    await run.command('ls running-mut/snooty');
I'm referring only to line 31 because `'ls running-mut/snooty` just lists all the files and directories within `running-mut/snooty`

2024-11-12 22:40 UTC, anabellabuckvar commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +      'cp -r AWSCLIV2.pkg build.sh bundle.zip CHANGELOG.md code-of-conduct.md component-factory-transformer docs-landing gatsby-browser.js gatsby-config.js gatsby-ssr.js jest.config.js jest-preproces
Not sure if it matters- @rayangler @branberry @seungpark , thoughts on this?

2024-11-13 19:14 UTC, branberry reviewed
Hey Bianca! Looking great! Just a few small comments

2024-11-13 19:14 UTC, branberry commented on redirects-and-publish/src/extension.ts
> +      {
This can be removed as well in favor of using the `util/extensions`

2024-11-13 19:14 UTC, branberry commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +      throw new Error('DocsetEntry information missing');
NIT: Could you make this more specific? Maybe add to this error message stating the values of each like so: 

```ts
throw new Error(`DocsetEntry information missing. bucket: ${docsetEntry?.bucket }, ...etc`);
```

2024-11-13 20:54 UTC, biancalaube commented on redirects-and-publish/src/mutRedirectsAndPublish.ts
> +      throw new Error('DocsetEntry information missing');
thanks for the suggestion!

2024-11-13 21:00 UTC, biancalaube commented on redirects-and-publish/src/extension.ts
> +      {
discussed on slack, going to do this in another ticket [DOP-5177](https://jira.mongodb.org/browse/DOP-5179)

2024-11-13 21:00 UTC, biancalaube commented on redirects-and-publish/src/assertDbEnvVars.ts
> +
discussed on slack, going to do this in another ticket [DOP-5177](https://jira.mongodb.org/browse/DOP-5179)

2024-11-14 17:49 UTC, branberry approved these changes
Looks great! Thank you

2024-11-15 16:24 UTC, merged